Passing audio struct instead of uint
Kosciany/MuVi pull request #15
Opened 2023-04-06 16:13 UTC by Kosciany

2023-04-16 06:58 UTC, pietruszewski requested changes

2023-04-16 06:58 UTC, pietruszewski commented on src/audio/AudioLoopbackWorker.cpp
> +                //std::cout <<"[AudioLoopback Worker] Pushing " << audio_buffer.buff[0] << std::endl;
To można wywalić

2023-04-16 06:58 UTC, pietruszewski commented on src/audio/AudioLoopbackWorker.cpp
> +                // std::cout << "[AudioLoopback Worker] Going to sleep for 1s\n";
To też można wywalić

2023-04-16 06:58 UTC, pietruszewski commented on src/audio/AudioLoopback.cpp
> +        // TODO: avoid generating FFAUDIO_EFORMAT in the first place
Takie todo można by było dodać do backloga. W sumie byłby fajny task, żeby spróbować przy użyciu Github Actions parsować wszystkie TODO i dodawać je do backloga

2023-04-16 06:58 UTC, pietruszewski commented on src/audio/AudioLoopback.cpp
> +    void fill_buffer(audiobuff_t *output_buffer, int size, T *input_buffer)
Typ argumentu do rozmiaru mógłbyś zmienić na size_t https://en.cppreference.com/w/cpp/types/size_t

2023-04-16 06:58 UTC, pietruszewski commented on src/audio/AudioLoopback.cpp
> +        }
Tutaj mógłbyś dodać couta z informacją o tym, że bufor wyjściowy jest za mały i będzie mniej próbek.

2023-04-17 07:50 UTC, Kosciany commented on src/audio/AudioLoopback.cpp
> +        // TODO: avoid generating FFAUDIO_EFORMAT in the first place
https://github.com/Kosciany/MuVi/issues/21

2023-04-24 14:01 UTC, pietruszewski approved these changes

2023-04-24 14:01 UTC, merged